Fix the error when run evaluation for segmentation cause by numpy
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject